import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Client } from "@notionhq/client";
import { Card } from "@/components/Card";
import { Nav } from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ database }) {
  return (
    <>
      <Head>
        <title>Notion testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav />
        <section>
          <h1>Rest API Test (Page)</h1>
          {database.map((d, i) => (
            <ul className="cards" key={i}>
              <li>
                <Link href={`/list/${d.id}`}>
                  <Card {...d} name={d.properties.Name.title[0].plain_text} />
                </Link>
              </li>
            </ul>
          ))}
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const notion = new Client({ auth: process.env.NOTION_API_KEY });
  const response = await notion.databases.query({
    database_id: process.env.NOTION_DATABASE_ID,
  });

  return {
    props: {
      database: response.results,
    },
    revalidate: 1,
  };
}
